container_units: 4

env:
  APP_SETTINGS: config.ProductionConfig
  DATABASE_URL: postgres://postgres:@localhost:5432/armonaut
  REDIS_URL: redis://localhost:6379/0
  SECRET_KEY: notasecret

cache:
  - pip
  - directories:
    - ${HOME}/.cache

redis: 4.0.2
postgresql: 9.6.2
python:
  - 3.6-dev
  - 3.7-dev
  - nightly

install:
  - psql -c 'create database armonaut;' -U postgres
  - python -m pip install pipenv
  - pipenv install
  - pipenv install --dev

script:
  - pytest --cov armonaut/ tests/

after_success:
  - codecov

branches:
  only:
    - master
