sudo: required
language: python

services:
  - redis-server
  - postgresql

env:
  - APP_SETTINGS=config.ProductionConfig
  - DATABASE_URL=postgres://postgres:@localhost:5432/armonaut
  - REDIS_URL=redis://localhost:6379/0

cache:
  - pip
  - directories:
    - ${HOME}/.cache

python:
  - 3.6
  - 3.7-dev
  - nightly

before_install:
  - psql -c 'create database armonaut;' -U postgres

install:
  - python -m pip install pipenv
  - pipenv install
  - pipenv install --dev

script:
  - pytest --cov armonaut/ tests/

notifications:
  email: false

branches:
  only:
    - master
