sudo: required
language: python

services:
  - redis-server
  - postgresql

env:
  global:
    - APP_SETTINGS=config.TestingConfig
    - DATABASE_URL=postgres://postgres:@localhost:5432/armonaut
    - REDIS_URL=redis://localhost:6379/0
    - SECRET_KEY=notasecret

    - GITHUB_OAUTH_ID=7c9836e4b56c5cd6d852
    - GITLAB_OAUTH_ID=664418d9f3984ef15a998bde3433a0704a2eee8303b7fbb7a0f8ff36372d286f
    - BITBUCKET_OAUTH_ID=2eRWALqLx4KpAvEZAv

cache:
  - pip
  - directories:
    - ${HOME}/.cache

python:
  - 3.6
  - 3.7-dev
  - nightly

before_install:
  - psql -c 'create database armonaut;' -U postgres

install:
  - python -m pip install pipenv
  - pipenv install
  - pipenv install --dev

script:
  - pytest --cov armonaut/ tests/ --vcr-record-mode=none

after_success:
  - codecov

notifications:
  email: false

branches:
  only:
    - master
