coverage:
  precision: 2
  round: down
  range: 80...90

  status:
    patch:
      target: 80%
      if_not_found: error

comment:
  layout: "header, diff, changes"
  behavior: new

coverage:
  notify:
    slack:
      default:
        url: " https://hooks.slack.com/services/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 "
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
